"""create user and blog tables

Revision ID: 1d46070f7f95
Revises: 280b59edb20a
Create Date: 2024-09-10 21:25:17.017205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d46070f7f95'
down_revision = '280b59edb20a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
