"""create user and blog tables

Revision ID: 280b59edb20a
Revises: 5f62ff85e9b0
Create Date: 2024-09-10 20:55:48.844731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280b59edb20a'
down_revision = '5f62ff85e9b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
