"""create user and blog tables

Revision ID: 2ab54e8267dc
Revises: 08a879d53dac
Create Date: 2024-09-10 12:59:19.341652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ab54e8267dc'
down_revision = '08a879d53dac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
