"""create user and blog tables

Revision ID: 5f62ff85e9b0
Revises: 9afe83ba1c7b
Create Date: 2024-09-10 19:20:57.437603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f62ff85e9b0'
down_revision = '9afe83ba1c7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
