"""create user and blog tables

Revision ID: 6aab73195f73
Revises: 2ab54e8267dc
Create Date: 2024-09-10 13:07:35.923128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aab73195f73'
down_revision = '2ab54e8267dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
