"""create user and blog tables

Revision ID: 7db0d2aa7f86
Revises: c7068cb06e06
Create Date: 2024-09-10 14:12:59.435853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db0d2aa7f86'
down_revision = 'c7068cb06e06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
