"""create user and blog tables

Revision ID: 9afe83ba1c7b
Revises: 7db0d2aa7f86
Create Date: 2024-09-10 14:23:29.976517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9afe83ba1c7b'
down_revision = '7db0d2aa7f86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
