"""create user and blog tables

Revision ID: c7068cb06e06
Revises: 6aab73195f73
Create Date: 2024-09-10 13:49:41.230867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7068cb06e06'
down_revision = '6aab73195f73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
